import test from "node:test";
import assert from "node:assert/strict";
import { createInMemoryRepositories } from "@/repositories/in-memory-repository";
import { startResearch } from "@/services/research-service";
import { startListingGeneration } from "@/services/listing-service";
import { getAiConfig } from "@/ai/provider-config";
import { listingGenerationSchema } from "@/ai/schemas";
function safeTask(task: { type:string; status:string; errorCode:string|null; errorMessage:string|null }) { return { taskType:task.type, taskStatus:task.status, taskErrorCode:task.errorCode, taskErrorMessage:(task.errorMessage||"").replace(/(key|token|authorization|bearer)[^ ]*/gi,"[redacted]").slice(0,240) }; }
test("real Amazon plus AI end-to-end chain",{skip:!(process.env.RUN_REAL_E2E === "1"&&process.env.SERPAPI_API_KEY&&process.env.AI_API_KEY)},async()=>{const repos=createInMemoryRepositories(); const product=await repos.products.create({name:process.env.SERPAPI_TEST_QUERY||"wireless charger",market:"US",channel:"Amazon"}); const started=Date.now(); const config=getAiConfig(); const researchTask=await startResearch(product.id,undefined,repos); if(researchTask.status!=="succeeded"){console.error(JSON.stringify({...safeTask(researchTask),aiProvider:config.provider,aiModel:config.model}));} assert.equal(researchTask.status,"succeeded"); const listingTask=await startListingGeneration(product.id,repos); if(listingTask.status!=="succeeded"){console.error(JSON.stringify({...safeTask(listingTask),aiProvider:config.provider,aiModel:config.model}));} assert.equal(listingTask.status,"succeeded"); const research=await repos.research.latestByProduct(product.id); const listing=await repos.listings.latestByProduct(product.id); assert.ok(research?.competitorCount); assert.ok(listing?.title); assert.equal(listingGenerationSchema.safeParse({title:listing.title,bulletPoints:listing.bullets,description:listing.description??"",keywords:listing.keywords}).success,true); console.log(JSON.stringify({competitorCount:research?.competitorCount,enrichmentSuccessCount:research?.stats.enrichmentSuccessCount,priceRange:research?.priceRange,researchPersisted:Boolean(research),researchUsage:research?.aiUsage,listingTitle:listing?.title,listingPersisted:Boolean(listing),listingUsage:listing?.aiUsage,listingSchemaValid:true,totalTaskElapsedMs:Date.now()-started}));});
