import test from "node:test";
import assert from "node:assert/strict";
import { createInMemoryRepositories } from "@/repositories/in-memory-repository";
import { startResearch } from "@/services/research-service";
import { startListingGeneration } from "@/services/listing-service";
import { getAiConfig } from "@/ai/provider-config";
import { listingGenerationSchema } from "@/ai/schemas";
import { PrismaClient } from "@prisma/client";
import { createPrismaRepositories } from "@/repositories/prisma-repository";
import { createTask } from "@/services/task-service";
import { taskQueue } from "@/task-queue/in-process-queue";
function safeTask(task: { type:string; status:string; errorCode:string|null; errorMessage:string|null }) { return { taskType:task.type, taskStatus:task.status, taskErrorCode:task.errorCode, taskErrorMessage:(task.errorMessage||"").replace(/(key|token|authorization|bearer)[^ ]*/gi,"[redacted]").slice(0,240) }; }
test("real Amazon plus AI end-to-end chain",{skip:!(process.env.RUN_REAL_E2E === "1"&&process.env.SERPAPI_API_KEY&&process.env.AI_API_KEY)},async()=>{const client=process.env.DATABASE_URL?new PrismaClient():null; const repos=client?createPrismaRepositories(client):createInMemoryRepositories(); const product=await repos.products.create({name:process.env.SERPAPI_TEST_QUERY||"wireless charger",market:"US",channel:"Amazon"}); const started=Date.now(); const config=getAiConfig(); const researchQueued=await createTask(product.id,"RESEARCH",undefined,repos); await taskQueue.enqueue(researchQueued.id); let researchTask=researchQueued; while(!["succeeded","failed"].includes(researchTask.status)){await new Promise(resolve=>setTimeout(resolve,1000)); researchTask=await repos.tasks.findById(researchQueued.id)??researchTask;} if(researchTask.status!=="succeeded"){console.error(JSON.stringify({...safeTask(researchTask),aiProvider:config.provider,aiModel:config.model}));} assert.equal(researchTask.status,"succeeded"); const listingQueued=await createTask(product.id,"LISTING_GENERATION",undefined,repos); await taskQueue.enqueue(listingQueued.id); let listingTask=listingQueued; while(!["succeeded","failed"].includes(listingTask.status)){await new Promise(resolve=>setTimeout(resolve,1000)); listingTask=await repos.tasks.findById(listingQueued.id)??listingTask;} if(listingTask.status!=="succeeded"){console.error(JSON.stringify({...safeTask(listingTask),aiProvider:config.provider,aiModel:config.model}));} assert.equal(listingTask.status,"succeeded"); const research=await repos.research.latestByProduct(product.id); const listing=await repos.listings.latestByProduct(product.id); assert.ok(research?.competitorCount); assert.ok(listing?.title); assert.equal(listingGenerationSchema.safeParse({title:listing.title,titleZh:listing.titleZh,bulletPoints:listing.bullets,bulletPointsZh:listing.bulletsZh,description:listing.description??"",descriptionZh:listing.descriptionZh,keywords:listing.keywords}).success,true); const fresh=client?createPrismaRepositories(new PrismaClient()):repos; const reloadResearch=await fresh.research.latestByProduct(product.id); const reloadListing=await fresh.listings.latestByProduct(product.id); console.log(JSON.stringify({competitorCount:research?.competitorCount,enrichmentSuccessCount:research?.stats.enrichmentSuccessCount,priceRange:research?.priceRange,researchPersisted:Boolean(research),researchUsage:research?.aiUsage,listingTitle:listing?.title,listingPersisted:Boolean(listing),listingUsage:listing?.aiUsage,listingSchemaValid:true,reloadAfterNewRepository:Boolean(reloadResearch&&reloadListing),totalTaskElapsedMs:Date.now()-started})); if(client)await client.$disconnect();});

