"use client";

import { useState } from "react";
import { activeProduct, products, tasks } from "@/lib/mock-data";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { ViewKey } from "@/lib/types";

type ViewProps = { navigate: (view: ViewKey) => void; toast: (message: string) => void };

function Heading({ eyebrow, title, description, action }: { eyebrow: string; title: React.ReactNode; description: string; action?: React.ReactNode }) {
  return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subheading">{description}</p></div>{action}</div>;
}
function Bottle({ small = false }: { small?: boolean }) { return <div className={`bottle ${small ? "small" : ""}`}><i /><b /><span>PURE<br /><em>WATER</em></span></div>; }

export function OverviewView({ navigate, toast }: ViewProps) {
  const [approved, setApproved] = useState(false);
  return <section className="page-view active"><Heading eyebrow="星期四，9 月 18 日" title={<>早上好，林晓 <span>👋</span></>} description="把下一个商品，从想法推进到可以销售的页面。" action={<Button onClick={() => toast("打开创建商品流程")}>＋ 创建商品</Button>} />
    <div className="kpi-grid"><Card className="kpi-card"><div className="kpi-icon purple">◇</div><div><span>商品项目</span><strong>3</strong><small>较上周 <b className="trend up">+1</b></small></div></Card><Card className="kpi-card"><div className="kpi-icon blue">◌</div><div><span>进行中任务</span><strong>2</strong><small>预计今天完成</small></div></Card><Card className="kpi-card"><div className="kpi-icon green">✓</div><div><span>平均 SEO 分数</span><strong>82</strong><small>较上周 <b className="trend up">+8</b></small></div></Card><Card className="kpi-card"><div className="kpi-icon orange">✦</div><div><span>本月用量</span><strong>68<small> / 100</small></strong><small>积分使用中</small></div></Card></div>
    <div className="section-title"><div><h2>商品工作流</h2><p>继续推进你的商品项目</p></div><button className="text-btn" onClick={() => navigate("products")}>查看全部商品 →</button></div>
    <div className="product-focus"><div className="product-preview"><div className="product-photo"><span className="photo-badge">主图</span><Bottle /><div className="leaf leaf-one" /><div className="leaf leaf-two" /></div><div className="product-info"><div className="status-row"><span className="status-pill in-progress">进行中</span><span className="muted">最后编辑于 {activeProduct.updatedAt}</span></div><h3>{activeProduct.name}</h3><p>{activeProduct.subtitle}</p><div className="tag-row"><span>{activeProduct.channel}</span><span>{activeProduct.market}</span><span>新品验证</span></div></div><button className="more-btn">•••</button></div><div className="workflow"><div className="workflow-head"><span>完成度</span><strong>54%</strong></div><Progress value={54} className="large" /><div className="steps">{[["research", "✓", "竞品研究", "已完成"], ["listing", "✓", "Listing 文案", "已完成"], ["assets", "3", "生成素材", "等待确认"], ["store", "4", "创建商品页", "未开始"], ["seo", "5", "SEO 优化", "未开始"]].map(([key, icon, label, state], index) => <button key={key} className={`step ${index < 2 ? "done" : index === 2 ? "current" : ""}`} onClick={() => navigate(key as ViewKey)}><span>{icon}</span><b>{label}</b><small>{state}</small></button>)}</div><Button variant="outline" className="full" onClick={() => navigate("assets")}>继续生成素材 <span>→</span></Button></div></div>
    <div className="lower-grid"><section><div className="section-title compact"><div><h2>市场机会</h2><p>来自最近一次竞品研究</p></div><button className="text-btn" onClick={() => navigate("research")}>查看研究 →</button></div><div className="insight-grid"><Card className="insight-card"><div className="insight-label"><span className="insight-icon coral">¥</span><span>主流价格带</span></div><strong>$28 — $42</strong><p>你的建议定价 <b>$36.99</b></p><div className="sparkline">{[35, 50, 42, 70, 62, 85, 74].map(v => <i key={v} style={{ height: `${v}%` }} />)}</div></Card><Card className="insight-card"><div className="insight-label"><span className="insight-icon yellow">✦</span><span>高频卖点</span></div><strong>过滤速度快</strong><p>在 78% 的好评中出现</p><div className="mini-bars"><i style={{ width: "78%" }} /><i style={{ width: "62%" }} /><i style={{ width: "46%" }} /></div></Card><Card className="insight-card"><div className="insight-label"><span className="insight-icon blue">!</span><span>用户痛点</span></div><strong>滤芯更换麻烦</strong><p>机会：做成一键替换结构</p><span className="pain-tag">差评提及 34 次</span></Card></div></section><section><div className="section-title compact"><div><h2>待你确认</h2><p>确认后 AI 才会继续下一步</p></div><span className="count-badge">{approved ? 1 : 2}</span></div><div className="approval-list"><article className="approval-item"><div className="approval-icon">Aa</div><div><b>确认 Listing 定位</b><p>“轻户外家庭净水”是否符合你的预期？</p><div><button className="small-btn approve" disabled={approved} onClick={() => { setApproved(true); toast("已确认，下一步任务可以继续"); }}>{approved ? "已确认" : "确认"}</button><button className="small-btn ghost">查看详情</button></div></div><span className="time">10 分钟前</span></article><article className="approval-item"><div className="approval-icon image">▧</div><div><b>选择主图风格</b><p>AI 已生成 3 个方向，等你挑选</p><div><button className="small-btn approve" onClick={() => navigate("assets")}>去选择</button></div></div><span className="time">32 分钟前</span></article></div></section></div>
  </section>;
}

export function ProductsView({ navigate, toast }: ViewProps) { return <section className="page-view active"><Heading eyebrow="商品中心" title="我的商品" description="所有商品项目都在这里继续推进。" action={<Button onClick={() => toast("打开创建商品流程")}>＋ 创建商品</Button>} /><div className="filter-row"><div className="search-field">⌕ <input placeholder="搜索商品名称" /></div><button className="filter-btn">全部状态⌄</button><button className="filter-btn">全部渠道⌄</button></div><div className="product-table"><div className="table-head"><span>商品</span><span>当前阶段</span><span>完成度</span><span>更新时间</span><span /></div>{products.map(product => <div className="table-row" key={product.id}><div className="table-product"><div className="tiny-product">▥</div><div><b>{product.name}</b><small>{product.channel} · {product.market}</small></div></div><span className={`status-pill ${product.status === "已发布" ? "done" : product.status === "待开始" ? "ready" : "in-progress"}`}>{product.status === "进行中" ? "生成素材" : product.status}</span><div className="table-progress"><span><i style={{ width: `${product.progress}%` }} /></span><b>{product.progress}%</b></div><span className="muted">{product.updatedAt}</span><button className="row-action" onClick={() => navigate("overview")}>打开 →</button></div>)}</div></section>; }

export function ResearchView({ navigate, toast }: ViewProps) { const [running, setRunning] = useState(false); return <section className="page-view active"><Heading eyebrow="便携式净水滤芯水壶 / 市场智能" title="竞品研究" description="把采集到的数据转成下一步可执行的商品决策。" action={<Button variant="outline" disabled={running} onClick={() => { setRunning(true); toast("正在重新分析竞品和用户评论"); setTimeout(() => { setRunning(false); toast("研究完成，发现 2 个新的卖点机会"); }, 1200); }}>{running ? "研究进行中…" : "↻ 重新研究"}</Button>} /><div className="research-hero"><div><span className="status-pill done">研究已完成</span><h2>这个市场还有机会，但要赢在“轻”和“快”。</h2><p>我们分析了 Amazon US 上 24 个相关商品、8,420 条评论和 312 个高频关键词。</p></div><div className="research-number"><strong>24</strong><span>竞品样本</span></div><div className="research-number"><strong>82%</strong><span>数据覆盖度</span></div></div><div className="research-grid"><Card className="panel"><div className="panel-title"><h3>价格分布</h3><span>Amazon US · USD</span></div><div className="price-chart"><div className="axis"><span>$50</span><span>$40</span><span>$30</span><span>$20</span></div><div className="bars">{[[28, "$24"], [45, "$29"], [77, "$36.99"], [65, "$39"], [88, "$45"]].map(([height, value], i) => <i className={i === 2 ? "highlight" : ""} style={{ height: `${height}%` }} key={value as string}><b>{value}</b></i>)}</div></div><div className="chart-note"><span />建议定价位于主流区间中段，兼顾转化与利润</div></Card><Card className="panel"><div className="panel-title"><h3>卖点机会</h3><span>基于评论语义聚类</span></div><div className="opportunity">{[["01", "过滤速度快", "78% 好评提及 · 可视化水流", "高"], ["02", "一键更换滤芯", "用户痛点 · 差评 34 次", "高"], ["03", "适配冰箱门", "竞品普遍忽略的场景", "中"]].map(([rank, title, detail, level]) => <div className="opportunity-item" key={rank}><span className="rank">{rank}</span><div><b>{title}</b><small>{detail}</small></div><strong>{level}</strong></div>)}</div><Button variant="outline" className="full" onClick={() => navigate("listing")}>根据机会生成 Listing →</Button></Card></div><Card className="panel table-panel"><div className="panel-title"><h3>高频搜索词</h3><button className="text-btn">查看全部 312 个 →</button></div><div className="keyword-list">{[["water filter pitcher", "9.2k"], ["fridge water filter", "6.8k"], ["portable water purifier", "4.1k"], ["fast water filtration", "2.7k"], ["water pitcher for travel", "1.9k"]].map(([word, count]) => <span key={word}>{word} <b>{count}</b></span>)}</div></Card></section>; }

export function ListingView({ toast }: ViewProps) { const [title, setTitle] = useState("PureFlow 便携式净水滤芯水壶，快速过滤饮用水，适配冰箱门，含 2 枚可替换滤芯，适合家庭与旅行使用"); const [generating, setGenerating] = useState(false); return <section className="page-view active"><Heading eyebrow="便携式净水滤芯水壶 / AI 创作" title="Listing 文案" description="结合竞品机会和你的定位，生成可直接编辑的商品文案。" action={<Button disabled={generating} onClick={() => { setGenerating(true); toast("AI 正在结合市场机会生成新版本"); setTimeout(() => { setTitle("PureFlow 便携式净水滤芯水壶，2.4 倍快速过滤，冰箱门适配，一键更换滤芯，适合家庭与户外旅行"); setGenerating(false); toast("Listing 版本 4 已生成，可继续编辑"); }, 1200); }}>{generating ? "✦ 生成中…" : "✦ 生成新版本"}</Button>} /><div className="editor-layout"><div className="editor-main"><div className="version-row"><span className="status-pill done">已生成</span><span>版本 3 · 2 分钟前</span><button className="text-btn">版本记录⌄</button></div><label>商品标题 <span>Amazon US · {title.length} / 200 字符</span><textarea value={title} onChange={event => setTitle(event.target.value)} /></label><label>五点描述 <span>5 / 5</span><div className="bullet-editor"><p>⚡ <b>快速过滤：</b>升级滤芯结构，几分钟内即可获得清爽好水。</p><p>♻ <b>轻松更换：</b>一键旋拧即可替换滤芯，不需要额外工具。</p><p>❄ <b>冰箱友好：</b>窄身设计可放入大多数冰箱门侧储物格。</p><p>✈ <b>轻便易携：</b>适合家庭、办公室和周末露营等多种场景。</p><p>💧 <b>安心饮水：</b>帮助减少氯味和常见杂质，保留自然口感。</p></div></label><label>关键词 <span>已覆盖 8 / 10 个高频词</span><div className="keyword-input"><span>water filter pitcher ×</span><span>portable purifier ×</span><span>fast filtration ×</span><input placeholder="添加关键词" /></div></label><div className="editor-footer"><span>所有修改将自动保存</span><Button onClick={() => toast("Listing 版本已保存")}>保存版本</Button></div></div><aside className="editor-side"><div className="score-card"><div className="score-ring"><strong>86</strong><span>/100</span></div><div><b>内容评分</b><p>比上个版本提升 12 分</p></div></div><div className="tip-list"><h3>AI 优化建议</h3><div><span>✓</span><p>标题已包含核心关键词</p></div><div><span>✓</span><p>五点描述覆盖 3 个用户痛点</p></div><div className="warning"><span>!</span><p>建议补充“BPA Free”安全材质信息</p></div></div></aside></div></section>; }

export function AssetsView({ toast }: ViewProps) { const [selected, setSelected] = useState(0); const [generating, setGenerating] = useState(false); const assets = [["主图 · 已选", "清透白底 · 产品正面", "asset-main"], ["场景图", "现代厨房 · 冰箱旁", "asset-kitchen"], ["场景图", "户外露营 · 轻便携带", "asset-travel"], ["广告图", "快速过滤 · 卖点海报", "asset-ad"]]; return <section className="page-view active"><Heading eyebrow="便携式净水滤芯水壶 / AI 创作" title="商品素材" description="选择渠道和画面方向，快速生成可以投放的素材。" action={<Button disabled={generating} onClick={() => { setGenerating(true); toast("正在生成 4 张商品素材"); setTimeout(() => { setGenerating(false); toast("素材生成完成，已加入素材库"); }, 1300); }}>{generating ? "✦ 生成中…" : "✦ 生成素材"}</Button>} /><div className="asset-toolbar"><div className="segmented"><button className="active">全部素材 <b>8</b></button><button>主图 <b>3</b></button><button>场景图 <b>3</b></button><button>广告图 <b>2</b></button></div><button className="filter-btn">Amazon US ⌄</button></div><div className="asset-grid">{assets.map(([label, name, style], index) => <article className={`asset-card ${selected === index ? "selected" : ""}`} key={name} onClick={() => { setSelected(index); toast("已选择这张素材作为主图候选"); }}><div className={`asset-image ${style}`}><span className="asset-label">{selected === index ? `${label.split(" · ")[0]} · 已选` : label}</span><Bottle small /></div><div className="asset-card-body"><b>{name}</b><span>{index === 0 || index === 3 ? "1:1 · 2000×2000 px" : "4:5 · 1600×2000 px"}</span></div></article>)}</div></section>; }

export function StoreView({ toast }: ViewProps) { const [published, setPublished] = useState(false); return <section className="page-view active"><Heading eyebrow="便携式净水滤芯水壶 / 独立站" title="商品页预览" description="把已经确认的内容组合成一页可以销售的商品页面。" action={<Button disabled={published} onClick={() => { setPublished(true); toast("商品页已发布，可以打开预览"); }}>{published ? "已发布 ✓" : "发布商品页"}</Button>} /><div className="store-preview-wrap"><div className="store-browser"><div className="browser-bar"><span /><span /><span /><small>pureflow-store.demo</small></div><div className="store-page"><div className="store-nav"><b>PUREFLOW</b><span>产品　为什么选择我们　FAQ</span><button>立即购买</button></div><div className="store-hero"><div><span className="store-kicker">PURE WATER · EVERYWHERE</span><h2>把纯净水，<br /><em>带到每一个地方。</em></h2><p>一款为轻户外生活设计的便携式净水滤芯水壶，快速、轻便、安心。</p><button className="store-cta">了解 PureFlow <span>→</span></button></div><div className="store-product"><Bottle /><div className="store-orb" /></div></div><div className="store-proof"><span>✓ 30 天无忧退货</span><span>✓ BPA Free 材质</span><span>✓ 过滤速度提升 2.4×</span></div></div></div><aside className="store-side"><div><h3>页面状态</h3><span className={`status-pill ${published ? "done" : "ready"}`}>{published ? "已发布" : "草稿"}</span></div><div className="store-check"><p><span>✓</span> 商品信息已同步</p><p><span>✓</span> 主图已选择</p><p><span>○</span> 绑定域名</p><p><span>○</span> 发布设置</p></div><Button variant="outline" className="full" onClick={() => toast("页面编辑器将在下一版开放，当前展示预览流程")}>编辑页面</Button></aside></div></section>; }

export function SeoView({ toast }: ViewProps) { const [auditing, setAuditing] = useState(false); return <section className="page-view active"><Heading eyebrow="便携式净水滤芯水壶 / 增长" title="SEO 优化" description="发布前做一次快速审计，让商品更容易被搜到和理解。" action={<Button disabled={auditing} onClick={() => { setAuditing(true); toast("正在检查页面结构、关键词和图片描述"); setTimeout(() => { setAuditing(false); toast("审计完成，发现 1 个高优先级问题"); }, 1200); }}>{auditing ? "审计中…" : "✦ 运行审计"}</Button>} /><div className="seo-overview"><div className="seo-score-big"><div className="score-ring large"><strong>82</strong><span>/100</span></div><div><span className="status-pill ready">良好</span><h2>还有 4 个机会可以提升</h2><p>完成高优先级建议后，预计可达到 94 分。</p></div></div><div className="seo-metrics"><div><b>12</b><span>已通过</span></div><div><b>3</b><span>待优化</span></div><div><b>1</b><span>需修复</span></div></div></div><div className="seo-list"><article className="seo-item critical"><div className="seo-status">!</div><div><span>高优先级</span><h3>Meta Description 缺少核心卖点</h3><p>加入“快速过滤”和“适配冰箱门”，让搜索摘要更有吸引力。</p></div><button className="small-btn approve" onClick={() => toast("已生成修复建议，请确认后应用")}>一键修复</button></article><article className="seo-item warning"><div className="seo-status">!</div><div><span>中优先级</span><h3>图片缺少 2 个 ALT 文本</h3><p>为厨房场景图和户外场景图添加描述，帮助图片搜索理解内容。</p></div><button className="small-btn ghost">去编辑</button></article><article className="seo-item good"><div className="seo-status">✓</div><div><span>已通过</span><h3>商品标题包含主要关键词</h3><p>“water filter pitcher” 已出现在标题前 80 个字符内。</p></div><span className="done-label">已完成</span></article></div></section>; }

export function TasksView(props: ViewProps) { void props; return <section className="page-view active"><Heading eyebrow="工作台" title="任务记录" description="查看所有研究、生成和发布任务的状态。" action={<button className="filter-btn">最近 30 天⌄</button>} /><div className="task-list">{tasks.map(task => <div className="task-row" key={task.id}><span className={`task-icon ${task.status === "succeeded" ? "green" : task.status === "running" ? "purple" : task.status === "queued" ? "orange" : "blue"}`}>{task.status === "succeeded" ? "✓" : task.status === "running" ? "✦" : task.status === "queued" ? "◌" : "▧"}</span><div><b>{task.title}</b><small>{task.detail}</small></div><span className="task-time">{task.time}</span><span className={`status-pill ${task.status === "succeeded" ? "done" : task.status === "running" ? "in-progress" : "ready"}`}>{task.status === "succeeded" ? "已完成" : task.status === "running" ? "需确认" : "待开始"}</span></div>)}</div></section>; }

export function SettingsView({ toast }: ViewProps) { return <section className="page-view active"><Heading eyebrow="工作台" title="设置" description="管理工作区、集成和用量。" /><div className="settings-grid"><div className="settings-nav"><button className="active">工作区设置</button><button>集成与 API</button><button>用量与账单</button><button>账户信息</button></div><div className="panel settings-panel"><h3>工作区设置</h3><label>工作区名称<input defaultValue="Lin 的工作区" /></label><label>默认市场<select defaultValue="us"><option value="us">美国 · Amazon US</option><option value="uk">英国 · Amazon UK</option></select></label><label>默认语言<select defaultValue="zh"><option value="zh">中文（简体）</option><option value="en">English</option></select></label><Button onClick={() => toast("设置已保存")}>保存设置</Button></div></div></section>; }
