import { normalizeCompetitorProducts } from "../normalize";
import type { MarketplaceProvider, MarketplaceQuery, MarketplaceProviderResult, CompetitorProduct } from "../types";

export type SerpApiErrorCode = "INVALID_CONFIGURATION"|"AUTHENTICATION_FAILURE"|"QUOTA_OR_RATE_LIMIT"|"TIMEOUT"|"UPSTREAM_5XX"|"MALFORMED_RESPONSE"|"EMPTY_SEARCH_RESULT"|"ENRICHMENT_FAILURE";
export class SerpApiProviderError extends Error { constructor(readonly code:SerpApiErrorCode,message:string){super(message); this.name="SerpApiProviderError";} }
type FetchLike=(input:RequestInfo|URL, init?:RequestInit)=>Promise<Response>;
export class SerpApiAmazonProvider implements MarketplaceProvider {
 readonly name="serpapi";
 constructor(private readonly apiKey:string, private readonly options:{domain?:string;language?:string;timeoutMs?:number;enrichmentLimit?:number;fetcher?:FetchLike}={}){}
 private async request(params:Record<string,string>):Promise<Record<string,unknown>> { const fetcher=this.options.fetcher??fetch; const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),this.options.timeoutMs??Number(process.env.MARKETPLACE_TIMEOUT_MS||8000)); try {const url=new URL("https://serpapi.com/search.json"); Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v)); url.searchParams.set("api_key",this.apiKey); const response=await fetcher(url,{signal:controller.signal}); if(response.status===401||response.status===403)throw new SerpApiProviderError("AUTHENTICATION_FAILURE","SerpApi authentication failed"); if(response.status===429)throw new SerpApiProviderError("QUOTA_OR_RATE_LIMIT","SerpApi quota or rate limit reached"); if(response.status>=500)throw new SerpApiProviderError("UPSTREAM_5XX","SerpApi upstream error"); if(!response.ok)throw new SerpApiProviderError("MALFORMED_RESPONSE",`SerpApi HTTP ${response.status}`); const payload=await response.json() as Record<string,unknown>; if(typeof payload!=="object"||payload===null)throw new SerpApiProviderError("MALFORMED_RESPONSE","SerpApi response was not an object"); return payload;} catch(error){if(error instanceof SerpApiProviderError)throw error; if(error instanceof Error&&error.name==="AbortError")throw new SerpApiProviderError("TIMEOUT","SerpApi request timed out"); throw new SerpApiProviderError("MALFORMED_RESPONSE","Unable to parse SerpApi response");} finally {clearTimeout(timer);} }
 async search(input:MarketplaceQuery):Promise<MarketplaceProviderResult>{if(!this.apiKey)throw new SerpApiProviderError("INVALID_CONFIGURATION","SERPAPI_API_KEY is required"); const query=input.query; let payload:Record<string,unknown>|undefined; let last:unknown; for(let attempt=0;attempt<3;attempt++){try{payload=await this.request({engine:"amazon",k:query,amazon_domain:this.options.domain??process.env.SERPAPI_AMAZON_DOMAIN??"amazon.com",language:this.options.language??process.env.SERPAPI_LANGUAGE??"en_US"}); break;}catch(error){last=error;if(error instanceof SerpApiProviderError&&["AUTHENTICATION_FAILURE","INVALID_CONFIGURATION","MALFORMED_RESPONSE"].includes(error.code))throw error;if(attempt<2)await new Promise(r=>setTimeout(r,200*(attempt+1)));}} if(!payload)throw last instanceof Error?last:new SerpApiProviderError("UPSTREAM_5XX","SerpApi request failed"); const fetchedAt=new Date().toISOString(); const organic=Array.isArray(payload.organic_results)?payload.organic_results:[]; const sponsored=Array.isArray(payload.sponsored_results)?payload.sponsored_results:[]; const rows=[...organic.map((x)=>({...(x as Record<string,unknown>),sponsored:false})),...sponsored.map((x)=>({...(x as Record<string,unknown>),sponsored:true}))]; const products=normalizeCompetitorProducts(rows,input.marketplace??(this.options.domain??"amazon.com"),fetchedAt).slice(0,input.limit??10); if(!products.length)throw new SerpApiProviderError("EMPTY_SEARCH_RESULT","SerpApi returned no Amazon products"); const candidates=products.slice(0,this.options.enrichmentLimit??Number(process.env.SERPAPI_ENRICHMENT_LIMIT||5)); let enrichmentSuccessCount=0; const enriched=await Promise.all(candidates.map(async p=>{try{const value=await this.enrich(p); enrichmentSuccessCount++; return value;}catch{return p;}})); return {products:[...enriched,...products.slice(enriched.length)],marketplace:input.marketplace??(this.options.domain??"amazon.com"),query,fetchedAt,enrichmentSuccessCount}; }
 private async enrich(product:CompetitorProduct):Promise<CompetitorProduct>{const payload=await this.request({engine:"amazon_product",asin:product.externalId,amazon_domain:this.options.domain??process.env.SERPAPI_AMAZON_DOMAIN??"amazon.com",language:this.options.language??process.env.SERPAPI_LANGUAGE??"en_US"}); const info=(payload.product_results??payload) as Record<string,unknown>; const merged={...product,brand:info.brand??product.brand,manufacturer:info.manufacturer??product.manufacturer,description:info.description??product.description,features:info.bullet_points??info.features??product.features,price:info.price??product.price,availability:info.availability??product.availability}; return normalizeCompetitorProducts([merged],product.marketplace,product.fetchedAt)[0]??product; }
}


