import type { ListingAdapter } from "@/adapters/types";
import { getListingAdapter } from "@/adapters/ai";
import { getRepositories } from "@/repositories";
import type { ListingCreateInput, RepositoryBundle } from "@/repositories/types";
import { createTask, executeTask } from "./task-service";
export async function saveListing(productId:string,input:Omit<ListingCreateInput,"productId">,repositories:RepositoryBundle=getRepositories()){return repositories.listings.create({...input,productId});}
export async function getLatestListing(productId:string,repositories:RepositoryBundle=getRepositories()){return repositories.listings.latestByProduct(productId);}
export async function runListingTask(taskId:string,productId:string,repositories:RepositoryBundle=getRepositories(),adapter:ListingAdapter=getListingAdapter()){const research=await repositories.research.latestByProduct(productId); const completed=await executeTask(taskId,async()=>{if(!research)throw new Error("RESEARCH_REQUIRED"); const result=await adapter.generateListing({productName:productId,research}); if(result.state!=="succeeded"||!result.data)throw new Error(result.error?.message??"AI_LISTING_FAILED"); return result;},repositories); if(completed.status==="succeeded"&&completed.output&&typeof completed.output==="object"){const result=completed.output as {data?:{title:string;bulletPoints:string[];description:string;keywords:string[]};usage?:unknown}; const output=result.data??(completed.output as {title:string;bulletPoints:string[];description:string;keywords:string[]}); await saveListing(productId,{taskId,title:output.title,bullets:output.bulletPoints,description:output.description,keywords:output.keywords,aiUsage:result.usage as never},repositories);} return completed;}
export async function startListingGeneration(productId:string,repositories:RepositoryBundle=getRepositories(),adapter:ListingAdapter=getListingAdapter()){const task=await createTask(productId,"LISTING_GENERATION",undefined,repositories); return runListingTask(task.id,productId,repositories,adapter);}
