import { snapshotCompetitors } from "./competitor-snapshot";
import type { CompetitorSnapshot } from "@/lib/types";
import type { ResearchAdapter } from "@/adapters/types";
import { getResearchAdapter } from "@/adapters/ai";
import { getMarketplaceProvider } from "@/marketplace/provider";
import { calculateCompetitorStats } from "@/marketplace/stats";
import { getRepositories } from "@/repositories";
import type { RepositoryBundle } from "@/repositories/types";
import type { ResearchAnalysis } from "@/ai/schemas";
import { createTask, executeTask } from "./task-service";
export type ResearchResult = ResearchAnalysis & { competitorSnapshot:CompetitorSnapshot[]; marketplace:string; query:string; competitorIds:string[]; fetchedAt:string; stats:Record<string,unknown> };
export async function runResearchTask(taskId:string, productId:string, adapter:ResearchAdapter=getResearchAdapter(), repositories:RepositoryBundle=getRepositories()){const completed=await executeTask(taskId,async()=>{const product=await repositories.products.findById(productId); if(!product) throw new Error("PRODUCT_NOT_FOUND"); const provider=getMarketplaceProvider(); const marketplace=await provider.search({query:product.name,marketplace:process.env.AMAZON_MARKETPLACE||"amazon",limit:10}); const stats={...calculateCompetitorStats(marketplace.products),enrichmentAttemptCount:provider.name==="serpapi"?marketplace.products.slice(0,Number(process.env.SERPAPI_ENRICHMENT_LIMIT||5)).length:0,enrichmentSuccessCount:marketplace.enrichmentSuccessCount??0,enrichmentFailureCount:marketplace.enrichmentFailures?.length??0,enrichmentFailures:marketplace.enrichmentFailures??[]}; const result=await adapter.analyzeCompetitor({productName:product.name,competitors:marketplace.products,stats}); if(result.state!=="succeeded"||!result.data)throw new Error(result.error?.message??"AI_RESEARCH_FAILED"); return {data:{...result.data,competitorCount:stats.competitorCount,priceRange:stats.priceRange,competitorSnapshot:snapshotCompetitors(marketplace,provider.name),marketplace:marketplace.marketplace,query:marketplace.query,competitorIds:marketplace.products.map(p=>p.externalId),fetchedAt:marketplace.fetchedAt,stats},usage:result.usage};},repositories); if(completed.status==="succeeded"){const wrapped=completed.output as {data:ResearchResult;usage?:unknown}; await repositories.research.create({productId,taskId:taskId,...wrapped.data,source:process.env.MARKETPLACE_PROVIDER==="serpapi"?"serpapi":"mock",aiUsage:wrapped.usage as never});} return completed;}
export async function startResearch(productId:string,adapter:ResearchAdapter=getResearchAdapter(),repositories:RepositoryBundle=getRepositories()){const task=await createTask(productId,"RESEARCH",undefined,repositories); return runResearchTask(task.id,productId,adapter,repositories);}

